name: Build project and run Lighthouse CI
on: [push]
jobs:
  deployment:
    environment: lhci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          yarn add ci
      - run: yarn build
      - run: |
          yarn global add @lhci/cli@0.9.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
